---------------------------------------------------------------------------------------------------------------------
--run this code if you're on terminal
-- switch to postgres database
--\c postgres;
-- drop and create database
--DROP DATABASE IF EXISTS university;
--CREATE DATABASE university;
--\c university;
---------------------------------------------------------------------------------------------------------------------
-- Drop View
DROP VIEW IF EXISTS v_full_course_workload;

-- Drop Trigger
DROP TRIGGER IF EXISTS employee_max_course_instances_per_period_and_year ON employee_activity;

-- Drop Function
DROP FUNCTION IF EXISTS check_teacher_max_course_instances();

-- Drop all tables 
DROP TABLE IF EXISTS person_address CASCADE;
DROP TABLE IF EXISTS phone_number CASCADE;
DROP TABLE IF EXISTS salary_history CASCADE;
DROP TABLE IF EXISTS skill CASCADE;
DROP TABLE IF EXISTS employee_activity CASCADE;
DROP TABLE IF EXISTS planned_activity CASCADE;
DROP TABLE IF EXISTS course_instance CASCADE;
DROP TABLE IF EXISTS department CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS job_title CASCADE;
DROP TABLE IF EXISTS teaching_activity CASCADE;
DROP TABLE IF EXISTS course_layout CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS address CASCADE;

-- Drop types 
DROP TYPE IF EXISTS STUDY_PERIOD;
DROP TYPE IF EXISTS COUNTRY_NAME;
---------------------------------------------------------------------------------------------------------------------
-- ENUM TYPES
CREATE TYPE STUDY_PERIOD AS ENUM ('P1', 'P2', 'P3', 'P4');
CREATE TYPE COUNTRY_NAME AS ENUM ('Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bhutan', 'Bolivia', 'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Côte d''Ivoire', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada', 'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo (Congo-Brazzaville)', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia (Czech Republic)', 'Democratic Republic of the Congo', 'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar (formerly Burma)', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Korea', 'North Macedonia', 'Norway', 'Oman', 'Pakistan', 'Palau', 'Palestine State', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 'South Africa', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Tajikistan', 'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States of America', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe');
---------------------------------------------------------------------------------------------------------------------
-- PERSON PART OF THE MODEL
CREATE TABLE address (
  address_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  street_name VARCHAR(300) NOT NULL,
  zip VARCHAR(300) NOT NULL,
  city VARCHAR(300) NOT NULL,
  country COUNTRY_NAME NOT NULL
);

CREATE TABLE person (
  person_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  personal_number VARCHAR(12) UNIQUE NOT NULL,
  first_name VARCHAR(300) NOT NULL,
  last_name VARCHAR(300) NOT NULL
);

CREATE TABLE person_address (
  person_id INT NOT NULL,
  address_id INT NOT NULL,
  PRIMARY KEY (person_id, address_id),
  FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE RESTRICT ON UPDATE RESTRICT, --force user to update the db
  FOREIGN KEY (address_id) REFERENCES address(address_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE phone_number (
  phone_nb VARCHAR(10) NOT NULL,
  person_id INT NOT NULL,
  PRIMARY KEY (phone_nb, person_id),
  FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);
---------------------------------------------------------------------------------------------------------------------
--EMPLOYEE PART OF THE MODEL
CREATE TABLE job_title (
	job_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	job_title VARCHAR(300)
);

CREATE TABLE employee (
	employment_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	manager_id INT, --can be NULL if you have no manager
	person_id INT NOT NULL,
	job_id INT NOT NULL,
	department_id INT NOT NULL,
	--FOREIGN KEY (manager_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (person_id) REFERENCES person(person_id) ON DELETE 	RESTRICT ON UPDATE RESTRICT,
	FOREIGN KEY (job_id) REFERENCES job_title(job_id) ON DELETE RESTRICT ON UPDATE RESTRICT
	--FOREIGN KEY (department_id) REFERENCES department(department_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE department(
	department_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	department_name VARCHAR(300) UNIQUE NOT NULL,
	manager_id INT NOT NULL,
	FOREIGN KEY (manager_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE salary_history(
	salary_history_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	monthly_salary_amount VARCHAR(300),
	from_date TIMESTAMPTZ NOT NULL,
	to_date TIMESTAMPTZ, --can be Null
	employment_id INT NOT NULL,
	FOREIGN KEY (employment_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE skill(
	skill_name VARCHAR(300) NOT NULL,
	employment_id INT NOT NULL,
	PRIMARY KEY (skill_name, employment_id),
	FOREIGN KEY (employment_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE employee_activity (
	employment_id INT NOT NULL,
	planned_activity_id INT NOT NULL,
	PRIMARY KEY(employment_id, planned_activity_id),
	FOREIGN KEY (employment_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT
	--FOREIGN KEY (planned_activity_id) REFERENCES planned_activity(planned_activity_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

---------------------------------------------------------------------------------------------------------------------
-- COURSE PART OF THE MODEL

CREATE TABLE course_layout (
  course_layout_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  course_code INT NOT NULL,
  layout_version INT NOT NULL,
  course_name VARCHAR(300) NOT NULL,
  min_students INT NOT NULL,
  max_students INT NOT NULL,
  hp INT NOT null,
  CONSTRAINT unique_course_version UNIQUE (course_code, layout_version) --
);

CREATE TABLE teaching_activity (
  teaching_activity_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  activity_name VARCHAR(300) NOT null UNIQUE,
  factor FLOAT(10) NOT NULL
);

CREATE TABLE course_instance (
  instance_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  num_students INT NOT NULL,
  study_period STUDY_PERIOD NOT NULL,
  study_year INT NOT NULL,
  course_layout_id INT NOT NULL,
 FOREIGN KEY (course_layout_id ) REFERENCES course_layout(course_layout_id ) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE planned_activity (
  planned_activity_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
  planned_nb_hours INT NOT NULL,
  instance_id INT NOT NULL,
  teaching_activity_id INT NOT NULL,
  FOREIGN KEY (instance_id) REFERENCES course_instance(instance_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
  FOREIGN KEY (teaching_activity_id) REFERENCES teaching_activity(teaching_activity_id) ON DELETE RESTRICT ON UPDATE RESTRICT
);

--add foreign keys and avoid cyclic dependencies in postgres:
ALTER TABLE employee
	ADD CONSTRAINT fk_employee_manager
	FOREIGN KEY (manager_id) REFERENCES employee(employment_id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE employee
	ADD CONSTRAINT fk_employee_department
	FOREIGN KEY (department_id) REFERENCES department(department_id) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE employee_activity
	ADD CONSTRAINT fk_planned_activity_id
	FOREIGN KEY (planned_activity_id) REFERENCES planned_activity(planned_activity_id) ON DELETE RESTRICT ON UPDATE RESTRICT;

---------------------------------------------------------------------------------------------------------------------
-- add triggers
CREATE OR REPLACE FUNCTION check_teacher_max_course_instances()
RETURNS TRIGGER AS $$
DECLARE
    v_study_period  STUDY_PERIOD;
    v_study_year    INT;
    v_instance_id   INT;
    v_course_count  INT;
BEGIN
    SELECT ci.study_period, ci.study_year, ci.instance_id INTO v_study_period, v_study_year, v_instance_id
    FROM planned_activity pa
    JOIN course_instance ci ON pa.instance_id = ci.instance_id
    WHERE pa.planned_activity_id = NEW.planned_activity_id;

    SELECT COUNT(DISTINCT ci2.instance_id) INTO v_course_count
    FROM employee_activity ea
    JOIN planned_activity pa2 ON ea.planned_activity_id = pa2.planned_activity_id
    JOIN course_instance ci2 ON pa2.instance_id = ci2.instance_id
    WHERE ea.employment_id = NEW.employment_id
      AND ci2.study_period = v_study_period
      AND ci2.study_year = v_study_year;

IF v_course_count >= 4 
       AND NOT EXISTS (
           SELECT 1 FROM employee_activity ea
           JOIN planned_activity pa2 ON ea.planned_activity_id = pa2.planned_activity_id
           WHERE ea.employment_id = NEW.employment_id
             AND pa2.instance_id = v_instance_id
       ) THEN
        RAISE EXCEPTION 'Teacher % already has 4 course instances in study period % year %', NEW.employment_id, v_study_period, v_study_year;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER employee_max_course_instances_per_period_and_year
BEFORE INSERT ON employee_activity
FOR EACH ROW
EXECUTE FUNCTION check_teacher_max_course_instances();

-- view for derived data 
---------------------------------------------------------------------------------------------------------------------

CREATE OR REPLACE VIEW  v_full_course_workload AS

-- all the manually entered hours
SELECT
    pa.planned_activity_id,
    pa.instance_id,
    ta.activity_name,
    ta.factor,
    pa.planned_nb_hours,
   (pa.planned_nb_hours * ta.factor) AS total_teachers_hours
FROM
    planned_activity pa
JOIN
    teaching_activity ta ON pa.teaching_activity_id = ta.teaching_activity_id
WHERE
    ta.activity_name NOT IN ('Examination', 'Administration')

UNION ALL

-- calculate the Examination hours
SELECT
    NULL AS planned_activity_id, 
    ci.instance_id,
    'Examination' AS activity_name,
     NULL AS factor,
     NULL AS planned_nb_hours,
    (32 + 0.725 * ci.num_students) AS  total_teachers_hours 
FROM
    course_instance ci

UNION ALL

-- calculatethe Administration hours
SELECT
    NULL AS planned_activity_id,
    ci.instance_id,
    'Administration' AS activity_name,
     NULL AS factor,
     NULL AS planned_nb_hours,
    (2 * cl.hp + 28 + 0.2 * ci.num_students) AS total_teachers_hours 
FROM
    course_instance ci
JOIN
    course_layout cl ON ci.course_layout_id = cl.course_layout_id;
